import { useState } from 'react';
import Head from 'next/head';
import Header from 'components/Header';
import { MainContainer, SecondaryContainer } from 'components/Containers';
import { SideBar } from 'components/Navigation';
import Introduction from 'components/Introduction';
import CodeBlock, { functionList } from 'components/CodeBlock';

export default function Home() {
  const [isOpen, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Q-Sys | Remote Control | Docs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full h-full bg-gray-100 overflow-hidden">
        <MainContainer>
          <Header title="qsys-qrc-py" version="0.0.1" callback={setOpen} />
          <SecondaryContainer>
            <SideBar />
            <main className="bg-gray-700 w-full h-full overflow-y-auto">
              <div className="w-full h-full flex flex-col p-8 gap-4 text-gray-200">
                <div className="w-full h-full">
                  <Introduction />
                  {functionList.map(({ name, snippet, description, params }) => (
                    <CodeBlock key={name} funcName={name} snippet={snippet} description={description} params={params} />
                  ))}
                </div>
              </div>
            </main>
          </SecondaryContainer>
        </MainContainer>
      </div>
    </>
  )
}
